cleanup (#62)
* reset added route option

* add src IP for route option

* utilize docker layer caching more

* just always use iptables

* more DNS checks

diff --git a/wsl-vpnkit b/wsl-vpnkit
--- a/wsl-vpnkit
+++ b/wsl-vpnkit
@@ -17,8 +17,9 @@ VPNKIT_HIGHEST_IP="192.168.67.14"
 VPNKIT_WSL2_IP="$VPNKIT_LOWEST_IP"
 VPNKIT_DEBUG=
 WSL2_GATEWAY_IP="$(cat /etc/resolv.conf | awk '/^nameserver/ {print $2}')"
-USE_IPTABLES=1
 CHECK_HOST=example.com
+DNS_IP="$VPNKIT_GATEWAY_IP"
+CHECK_DNS=1.1.1.1
 
 echo "starting wsl-vpnkit"
 if [ -f "$CONF_PATH" ]; then
@@ -90,45 +91,53 @@ ipconfig () {
     echo "configuring ip..."
     ip a add $VPNKIT_WSL2_IP/255.255.255.0 dev $TAP_NAME
     ip link set dev $TAP_NAME up
-    ip route del $(ip route | grep default)
+    ip route | grep -e "$VPNKIT_GATEWAY_IP" -e 'default' | tr '\n' '\0' | xargs -0 -n 1 sh -c 'ip route del $1' argv0
     ip route add default via $VPNKIT_GATEWAY_IP dev $TAP_NAME
     echo "ip config done"
 
-    if [ "$USE_IPTABLES" ]; then
-        echo "adding rules to iptables..."
-        iptables -t nat -A PREROUTING -d $WSL2_GATEWAY_IP/32 -p udp -m udp --dport 53 -j DNAT --to-destination $VPNKIT_GATEWAY_IP:53
-        iptables -t nat -A PREROUTING -d $WSL2_GATEWAY_IP/32 -j DNAT --to-destination $VPNKIT_HOST_IP
-        iptables -t nat -A OUTPUT -d $WSL2_GATEWAY_IP/32 -p udp -m udp --dport 53 -j DNAT --to-destination $VPNKIT_GATEWAY_IP:53
-        iptables -t nat -A OUTPUT -d $WSL2_GATEWAY_IP/32 -j DNAT --to-destination $VPNKIT_HOST_IP
-        iptables -t nat -A POSTROUTING -o $TAP_NAME -j MASQUERADE
-        echo "iptables done"
-    else
-        echo "adding route for Windows host via VPNKit..."
-        ip route add $WSL2_GATEWAY_IP via $VPNKIT_GATEWAY_IP dev $TAP_NAME
-        echo "added route for Windows host via VPNKit"
-    fi
+    echo "adding rules to iptables..."
+    iptables -t nat -A PREROUTING -d $WSL2_GATEWAY_IP/32 -p udp -m udp --dport 53 -j DNAT --to-destination $DNS_IP:53
+    iptables -t nat -A PREROUTING -d $WSL2_GATEWAY_IP/32 -p tcp -m tcp --dport 53 -j DNAT --to-destination $DNS_IP:53
+    iptables -t nat -A PREROUTING -d $WSL2_GATEWAY_IP/32 -j DNAT --to-destination $VPNKIT_HOST_IP
+    iptables -t nat -A OUTPUT -d $WSL2_GATEWAY_IP/32 -p udp -m udp --dport 53 -j DNAT --to-destination $DNS_IP:53
+    iptables -t nat -A OUTPUT -d $WSL2_GATEWAY_IP/32 -p tcp -m tcp --dport 53 -j DNAT --to-destination $DNS_IP:53
+    iptables -t nat -A OUTPUT -d $WSL2_GATEWAY_IP/32 -j DNAT --to-destination $VPNKIT_HOST_IP
+    iptables -t nat -A POSTROUTING -o $TAP_NAME -j MASQUERADE
+    echo "iptables done"
 }
 
 check_ping () {
-    ping -$1 -c 1 $3 >/dev/null && echo "check: ping success to $2 ($3) IPv$1" || echo "check: ping fail$([[ $1 = '6' ]] && echo ' as expected') to $2 ($3) IPv$1"
+    ping -$1 -c 1 $3 >/dev/null && \
+        echo "check: ✔️ ping success to IPv$1 $2 ($3)" || \
+        echo "check: $([[ $1 = '6' ]] && echo '➖' || echo '❌') ping fail to IPv$1 $2 ($3)"
 }
 
 check_dns () {
     TYPE=$([[ "$1" = "4" ]] && echo 'A' || echo 'AAAA')
-    nslookup -type=$TYPE $2 >/dev/null && echo "check: nslookup success for $2 $TYPE" || echo "check: nslookup fail for $2 $TYPE"
+    nslookup -type=$TYPE $2 $3 >/dev/null && \
+        echo "check: ✔️ nslookup success for $2 $TYPE using $3" || \
+        echo "check: ❌ nslookup fail for $2 $TYPE using $3"
 }
 
 check_https () {
-    wget --spider $1 && echo "check: wget success for $1" || echo "check: wget fail for $1"
+    wget --spider -q $1 && \
+        echo "check: ✔️ wget success for $1" || \
+        echo "check: ❌ wget fail for $1"
 }
 
 check () {
-    check_ping 4 'Windows host' $WSL2_GATEWAY_IP
-    check_ping 4 'Windows host' $VPNKIT_HOST_IP
+    check_ping 4 'WSL 2 gateway / Windows host' $WSL2_GATEWAY_IP
+    check_ping 4 'VPNKit Windows host' $VPNKIT_HOST_IP
     check_ping 4 'VPNKit gateway' $VPNKIT_GATEWAY_IP
-    check_dns 4 $CHECK_HOST
+    check_dns 4 $CHECK_HOST $DNS_IP
+    check_dns 4 $CHECK_HOST $VPNKIT_GATEWAY_IP
+    check_dns 4 $CHECK_HOST $WSL2_GATEWAY_IP
+    check_dns 4 $CHECK_HOST $CHECK_DNS
     check_ping 4 'external host' $CHECK_HOST
-    check_dns 6 $CHECK_HOST
+    check_dns 6 $CHECK_HOST $DNS_IP
+    check_dns 6 $CHECK_HOST $VPNKIT_GATEWAY_IP
+    check_dns 6 $CHECK_HOST $WSL2_GATEWAY_IP
+    check_dns 6 $CHECK_HOST $CHECK_DNS
     check_ping 6 'external host' $CHECK_HOST
     check_https "https://$CHECK_HOST"
 }
@@ -141,6 +150,7 @@ cleanup () {
     echo "iptables cleanup done"
 
     echo "cleaning up ip..."
+    ip route | grep -e "$VPNKIT_GATEWAY_IP" -e 'default' | tr '\n' '\0' | xargs -0 -n 1 sh -c 'ip route del $1' argv0
     ip link set dev $TAP_NAME down
     ip route add default via $WSL2_GATEWAY_IP dev eth0
     echo "ip cleanup done"
