add connectivity checks to log (#59)

diff --git a/wsl-vpnkit b/wsl-vpnkit
--- a/wsl-vpnkit
+++ b/wsl-vpnkit
@@ -18,6 +18,7 @@ VPNKIT_WSL2_IP="$VPNKIT_LOWEST_IP"
 VPNKIT_DEBUG=
 WSL2_GATEWAY_IP="$(cat /etc/resolv.conf | awk '/^nameserver/ {print $2}')"
 USE_IPTABLES=1
+CHECK_HOST=example.com
 
 echo "starting wsl-vpnkit"
 if [ -f "$CONF_PATH" ]; then
@@ -108,6 +109,30 @@ ipconfig () {
     fi
 }
 
+check_ping () {
+    ping -$1 -c 1 $3 >/dev/null && echo "check: ping success to $2 ($3) IPv$1" || echo "check: ping fail$([[ $1 = '6' ]] && echo ' as expected') to $2 ($3) IPv$1"
+}
+
+check_dns () {
+    TYPE=$([[ "$1" = "4" ]] && echo 'A' || echo 'AAAA')
+    nslookup -type=$TYPE $2 >/dev/null && echo "check: nslookup success for $2 $TYPE" || echo "check: nslookup fail for $2 $TYPE"
+}
+
+check_https () {
+    wget --spider $1 && echo "check: wget success for $1" || echo "check: wget fail for $1"
+}
+
+check () {
+    check_ping 4 'Windows host' $WSL2_GATEWAY_IP
+    check_ping 4 'Windows host' $VPNKIT_HOST_IP
+    check_ping 4 'VPNKit gateway' $VPNKIT_GATEWAY_IP
+    check_dns 4 $CHECK_HOST
+    check_ping 4 'external host' $CHECK_HOST
+    check_dns 6 $CHECK_HOST
+    check_ping 6 'external host' $CHECK_HOST
+    check_https "https://$CHECK_HOST"
+}
+
 cleanup () {
     echo "cleaning up iptables..."
     iptables -t nat -S | grep $VPNKIT_GATEWAY_IP | cut -d " " -f 2- | tr '\n' '\0' | xargs -0 -r -n 1 sh -c 'iptables -t nat -D $1' argv0
@@ -147,6 +172,7 @@ relay_wait
 vpnkit &
 tap
 ipconfig
+check
 trap close exit
 trap exit int term
 wait
